version: 2.1

executors:
  cl2-back:
    parameters:
      image-tag:
        type: string
    docker:
      - image: citizenlabdotco/cl2-back:<< parameters.image-tag >>
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
      - image: 'camptocamp/postgres:9.6'
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

commands:
  wait-for-postgres:
    steps:
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1

jobs:

  build-docker-image:
    docker:
      - image: docker:stable-git
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          docker build -t citizenlabdotco/cl2-back:$CIRCLE_SHA1 .
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push citizenlabdotco/cl2-back:$CIRCLE_SHA1


  test:
    resource_class: small
    executor:
      name: cl2-back
      image-tag: $CIRCLE_SHA1
    working_directory: /cl2_back
    parallelism: 4
    environment:
      RAILS_ENV: test
      CITIZENLAB_EE: true
    steps:
      - checkout:
          path: /tmp/cl2-back
      - wait-for-postgres
      - run: |
          rake db:create
          rake db:schema:load
      - run: |
          TESTFILES=$(circleci tests glob "spec/**/*_spec.rb" "engines/*/spec/**/*_spec.rb" | circleci tests split  --split-by=timings)
          echo $TESTFILES
          bundle exec rspec --format documentation --format RspecJunitFormatter -o spec/reports/rspec.xml -- ${TESTFILES}
      - store_test_results:
          path: spec/reports

  license-check:
    resource_class: small
    executor:
      name: cl2-back
      image-tag: $CIRCLE_SHA1
    working_directory: /cl2_back
    steps:
      - run: license_finder

  slow-tests:
    resource_class: small
    executor:
      name: cl2-back
      image-tag: $CIRCLE_SHA1
    working_directory: /cl2_back
    environment:
      RAILS_ENV: test
      CITIZENLAB_EE: true
    steps:
      - checkout:
          path: /tmp/cl2-back
      - wait-for-postgres
      - run: |
          rake db:create
          rake db:schema:load
      - run: |
          bundle exec rspec --format documentation --format RspecJunitFormatter -o spec/reports/rspec.xml -t slow_test
      - store_test_results:
          path: spec/reports

  web-api-docs:
    resource_class: small
    executor:
      name: cl2-back
      image-tag: $CIRCLE_SHA1
    working_directory: /cl2_back
    environment:
      RAILS_ENV: test
      CITIZENLAB_EE: true
    steps:
      - checkout:
          path: /tmp/cl2-back
      - wait-for-postgres
      - run: |
          rake db:create
          rake db:schema:load
      - run: bundle exec rake web_api:docs:generate
      - run: bundle exec rake public_api:docs:generate
      - run: bundle exec rake admin_api:docs:generate
      - run: apt-get -y install awscli
      - run: aws s3 sync doc/api s3://developers.citizenlab.co/api-docs/frontweb_api/$CIRCLE_BRANCH --delete --acl public-read
      - run: aws s3 sync doc/public_api s3://developers.citizenlab.co/api-docs/public_api/$CIRCLE_BRANCH --delete --acl public-read
      - run: aws s3 sync doc/admin_api s3://developers.citizenlab.co/api-docs/admin_api/$CIRCLE_BRANCH --delete --acl public-read

  push-deployment-docker-image:
    resource_class: small
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker pull citizenlabdotco/cl2-back:$CIRCLE_SHA1
      - run: docker tag citizenlabdotco/cl2-back:$CIRCLE_SHA1 citizenlabdotco/cl2-back:$CIRCLE_BRANCH
      - deploy:
          command: docker push citizenlabdotco/cl2-back:$CIRCLE_BRANCH

  deploy-to-swarm:
    resource_class: small
    docker:
      - image: buildo/alpine-ssh
    parameters:
      ssh_host:
        type: string
      ssh_user:
        type: string
        default: ubuntu
      stack_name:
        type: string
        default: cl2-back
      compose_file:
        type: string
        default: docker-compose-production.yml
      env_file:
        type: string
        default: .env-production
    steps:
      - run:
          command: ssh << parameters.ssh_user >>@<< parameters.ssh_host >> -o StrictHostKeyChecking=no "docker pull citizenlabdotco/cl2-back:$CIRCLE_BRANCH && docker run --env-file cl2-deployment/<< parameters.env_file >> citizenlabdotco/cl2-back:$CIRCLE_BRANCH rake db:migrate cl2back:clean_tenant_settings email_campaigns:assure_campaign_records fix_existing_tenants:update_permissions cl2back:clear_cache_store email_campaigns:remove_deprecated"
      - deploy:
          command: ssh << parameters.ssh_user >>@<< parameters.ssh_host >> -o StrictHostKeyChecking=no "cd cl2-deployment && docker stack deploy --compose-file << parameters.compose_file >> << parameters.stack_name >> --with-registry-auth"

  check-for-inconsistent-data:
    resource_class: small
    docker:
      - image: buildo/alpine-ssh
    parameters:
      ssh_host:
        type: string
      ssh_user:
        type: string
        default: ubuntu
      stack_name:
        type: string
        default: cl2-back
      compose_file:
        type: string
        default: docker-compose-production.yml
      env_file:
        type: string
        default: .env-production
    steps:
      - run:
          name: Check for inconsistent data
          command: ssh << parameters.ssh_user >>@<< parameters.ssh_host >> -o StrictHostKeyChecking=no "docker run --env-file cl2-deployment/<< parameters.env_file >> citizenlabdotco/cl2-back:$CIRCLE_BRANCH rake checks:invalid_data"
          no_output_timeout: 60m


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-docker-image:
          context: docker-hub-access
          filters:
            branches:
              ignore:
                - crowdin_master
      - license-check:
          context: docker-hub-access
          requires:
            - build-docker-image
          filters:
            branches:
              ignore:
                - crowdin_master
      - test:
          context: docker-hub-access
          requires:
            - build-docker-image
          filters:
            branches:
              ignore:
                - crowdin_master
      - slow-tests:
          context: docker-hub-access
          requires:
            - build-docker-image
          filters:
            branches:
              only:
                - master
                - production
      - web-api-docs:
          context: docker-hub-access
          requires:
            - test
            - slow-tests
          filters:
            branches:
              ignore:
                - crowdin_master
      - push-deployment-docker-image:
          context: docker-hub-access
          requires:
            - test
            - slow-tests
          filters:
            branches:
              only:
                - master
                - production
      - deploy-to-swarm:
          requires:
            - test
            - slow-tests
            - push-deployment-docker-image
          filters:
            branches:
              only:
                - master
          ssh_host: "52.29.30.188"
          compose_file: docker-compose-staging.yml
          stack_name: cl2-back-stg
          env_file: ".env-staging"
      - deploy-to-swarm:
          requires:
            - test
            - push-deployment-docker-image
          filters:
            branches:
              only:
                - production
          ssh_host: "52.57.74.84"
          compose_file: docker-compose-production-benelux.yml
          stack_name: cl2-prd-bnlx-stack
          env_file: ".env-production-benelux"
      - deploy-to-swarm:
          requires:
            - test
            - push-deployment-docker-image
          filters:
            branches:
              only:
                - production
          ssh_host: "35.183.23.116"
          compose_file: docker-compose-production-canada.yml
          env_file: ".env-production-canada"
      - deploy-to-swarm:
          requires:
            - test
            - push-deployment-docker-image
          filters:
            branches:
              only:
                - production
          ssh_host: "52.67.181.38"
          compose_file: docker-compose-production.yml
          env_file: ".env-web"
          stack_name: "cl2"
      - deploy-to-swarm:
          requires:
            - test
            - push-deployment-docker-image
          filters:
            branches:
              only:
                - production
          ssh_host: "52.13.59.174"
          compose_file: docker-compose-production.yml
          env_file: ".env-web"
          stack_name: "cl2"
      - deploy-to-swarm:
          requires:
            - test
            - push-deployment-docker-image
          filters:
            branches:
              only:
                - production
          ssh_host: "35.179.69.215"
          compose_file: docker-compose-production.yml
          env_file: ".env-web"
          stack_name: "cl2"
  check-for-inconsistent-data:
    triggers:
      - schedule:
          cron: "0 2 * * 1"
          filters:
            branches:
              only:
                - production
    jobs:
      # Benelux
      - check-for-inconsistent-data:
          ssh_host: "52.57.74.84"
          compose_file: docker-compose-production-benelux.yml
          stack_name: cl2-prd-bnlx-stack
          env_file: ".env-production-benelux"
      # South America
      - check-for-inconsistent-data:
          ssh_host: "52.67.181.38"
          compose_file: docker-compose-production.yml
          env_file: ".env-web"
          stack_name: "cl2"
      # Canada
      - check-for-inconsistent-data:
          ssh_host: "35.183.23.116"
          compose_file: docker-compose-production-canada.yml
          env_file: ".env-production-canada"
      # US West
      - check-for-inconsistent-data:
          ssh_host: "52.13.59.174"
          compose_file: docker-compose-production.yml
          env_file: ".env-web"
          stack_name: "cl2"
      # UK
      - check-for-inconsistent-data:
          ssh_host: "35.179.69.215"
          compose_file: docker-compose-production.yml
          env_file: ".env-web"
          stack_name: "cl2"
